SELECT
    USERS.USER_ID,
    USERS.NICKNAME,
    CONCAT(USERS.CITY, ' ', USERS.STREET_ADDRESS1, ' ', USERS.STREET_ADDRESS2) AS '전체주소',
    CONCAT(SUBSTRING(USERS.TLNO, 1, 3), '-', SUBSTRING(USERS.TLNO, 4, 4), '-', SUBSTRING(USERS.TLNO, 8, 4)) AS '전화번호'
FROM USED_GOODS_BOARD AS BOARD
JOIN USED_GOODS_USER AS USERS ON BOARD.WRITER_ID = USERS.USER_ID
GROUP BY USERS.USER_ID, USERS.NICKNAME, USERS.CITY, USERS.STREET_ADDRESS1, USERS.STREET_ADDRESS2, USERS.TLNO
HAVING COUNT(BOARD.BOARD_ID) >= 3
ORDER BY USERS.USER_ID DESC;