SELECT YEAR(DIFFERENTIATION_DATE),
# 각 년도 별 최대값 계산하는 SELECT 문
(SELECT MAX(e2.SIZE_OF_COLONY)
    FROM ECOLI_DATA e2
    WHERE YEAR(e2.DIFFERENTIATION_DATE) = YEAR(e.DIFFERENTIATION_DATE)
) - e.SIZE_OF_COLONY AS YEAR_DEV, e.ID
FROM ECOLI_DATA e
ORDER BY YEAR(DIFFERENTIATION_DATE), YEAR_DEV